#ifndef __ADC_CFG_H
#define __ADC_CFG_H

#define ADC_VOLTAGE 0
#define ADC_CURRENT 1

#define NUMBER_OF_GROUPS 2
#define NUMBER_CHANNELS_OF_GROUP0 1
#define NUMBER_CHANNELS_OF_GROUP1 1
#define NUMBER_CHANNELS_OF_GROUP2 0
#define NUMBER_CHANNELS_OF_GROUP3 0
#define NUMBER_CHANNELS_OF_GROUP4 0
#define NUMBER_CHANNELS_OF_GROUP5 0
#define NUMBER_CHANNELS_OF_GROUP6 0
#define NUMBER_CHANNELS_OF_GROUP7 0

#define ADC_1 0
#define ADC_2 1
#define ADC_3 2

#define ADC_CHANNEL_0 0
#define ADC_CHANNEL_1 1
#define ADC_CHANNEL_2 2
#define ADC_CHANNEL_3 3
#define ADC_CHANNEL_4 4
#define ADC_CHANNEL_5 5
#define ADC_CHANNEL_6 6
#define ADC_CHANNEL_7 7
#define ADC_CHANNEL_8 8
#define ADC_CHANNEL_9 9
#define ADC_CHANNEL_10 10
#define ADC_CHANNEL_11 11
#define ADC_CHANNEL_12 12
#define ADC_CHANNEL_13 13
#define ADC_CHANNEL_14 14
#define ADC_CHANNEL_15 15

#define ADC_SAMPLING_TIME_1_5_CYCLES 0
#define ADC_SAMPLING_TIME_7_5_CYCLES 1
#define ADC_SAMPLING_TIME_13_5_CYCLES 2
#define ADC_SAMPLING_TIME_28_5_CYCLES 3
#define ADC_SAMPLING_TIME_41_5_CYCLES 4
#define ADC_SAMPLING_TIME_55_5_CYCLES 5
#define ADC_SAMPLING_TIME_71_5_CYCLES 6
#define ADC_SAMPLING_TIME_239_5_CYCLES 7

#define ADC_RESOLUTION_12_BIT 0

#define ADC_REFERENCE_0 0
#define ADC_REFERENCE_1 1
#define ADC_REFERENCE_2 2
#define ADC_REFERENCE_3 3
#define ADC_REFERENCE_4 4
#define ADC_REFERENCE_5 5
#define ADC_REFERENCE_6 6
#define ADC_REFERENCE_7 7
#define ADC_REFERENCE_8 8
#define ADC_REFERENCE_9 9
#define ADC_REFERENCE_10 10
#define ADC_REFERENCE_11 11
#define ADC_REFERENCE_12 12
#define ADC_REFERENCE_13 13
#define ADC_REFERENCE_14 14
#define ADC_REFERENCE_15 15

#define ADC_CLOCK_DIV_2 0
#define ADC_CLOCK_DIV_4 1
#define ADC_CLOCK_DIV_6 2
#define ADC_CLOCK_DIV_8 3

#define ADC_GROUP_0 0
#define ADC_GROUP_1 1
#define ADC_GROUP_2 2
#define ADC_GROUP_3 3
#define ADC_GROUP_4 4
#define ADC_GROUP_5 5
#define ADC_GROUP_6 6
#define ADC_GROUP_7 7

#define ADC_HWTRIGGER_TIM1_CC1 0
#define ADC_HWTRIGGER_TIM1_CC2 1
#define ADC_HWTRIGGER_TIM1_CC3 2
#define ADC_HWTRIGGER_TIM2_CC2 3
#define ADC_HWTRIGGER_TIM3_TRGO 4
#define ADC_HWTRIGGER_TIM4_CC4 5
#define ADC_HWTRIGGER_TIM4_CC4 5
#define ADC_HWTRIGGER_EXTI_TIM8_TRGO 6
#define ADC_SWTRIGGER_SWS 7

#define ADC_USING_NORMAL 0
#define ADC_USING_DMA 1

#define ADC_SCAN_MODE_DISABLE 0
#define ADC_SCAN_MODE_ENABLE 1

extern const Adc_ConfigType Adc_Configuration[NUMBER_OF_GROUPS];

extern uint16 adcValue0[2];
extern uint16 adcValue1[2];

#endif