#ifndef CAN_CFG_H
#define CAN_CFG_H

#include "Can.h"

#define CAN_1_CONTROLLER 0
#define CAN_2_CONTROLLER 1

#define NUMBER_OF_CAN_HW_UNITS 1
#define NUMBER_OF_CAN_CONTROLLERS 1

#define CAN_DEBUG_MODE_CONTINOUS 0
#define CAN_DEBUG_MODE_FREEZE 1

#define CAN_TIMER_TRIGGER_COMMUNICATION_MODE_DISABLE 0
#define CAN_TIMER_TRIGGER_COMMUNICATION_MODE_ENABLE 1

#define CAN_AUTO_BUS_OFF_MODE_DISABLE 0
#define CAN_AUTO_BUS_OFF_MODE_ENABLE 1

#define CAN_AUTO_WAKEUP_MODE_DISABLE 0
#define CAN_AUTO_WAKEUP_MODE_ENABLE 1

#define CAN_AUTO_RETRANSMISSION_ENABLE 0
#define CAN_AUTO_RETRANSMISSION_DISABLE 1

#define CAN_RECEIVE_FIFO_LOCKED_MODE_OVERWRITE 0
#define CAN_RECEIVE_FIFO_LOCKED_MODE_DISCARD 1

#define CAN_TRANSMIT_FIFO_PRIORITY_BY_ID 0
#define CAN_TRANSMIT_FIFO_PRIORITY_BY_ORDER 1

extern Can_ControllerStateType Can_ControllerState[NUMBER_OF_CAN_CONTROLLERS];
extern Can_ConfigType CanConfig;

#endif