#ifndef __CAN_CFG_H__
#define __CAN_CFG_H__

#include "Can.h"
#include "stm32f103xb.h"

#define CAN_MAX_CONTROLLER 1

#define CAN_1 0
#define CAN_2 1

#define CAN_CLOCK 8000000

#define CAN_STANDARD_ID 0
#define CAN_EXTENDED_ID 1

#define CAN_MODE_NORMAL 0x00
#define CAN_MODE_LOOPBACK 0x01
#define CAN_MODE_SILENT 0x02
#define CAN_MODE_SILENT_LOOPBACK 0x03

#define CAN_MULTIPLEX_OFF 0
#define CAN_MULTIPLEX_ON 1

#define CAN_EVENT_DETECT_POLLING 0
#define CAN_EVENT_DETECT_INTERRUPT 1

#define CAN_SW_TRIGGER 0
#define CAN_HW_TRIGGER 1

#define CAN_AUTO_WAKEUP_OFF 0
#define CAN_AUTO_WAKEUP_ON 1

#define CAN_RETRANSMISSION_OFF 0
#define CAN_RETRANSMISSION_ON 1

#define CAN_RECEIVE_FIFO_LOCKED_MODE_OFF 0
#define CAN_RECEIVE_FIFO_LOCKED_MODE_ON 1

#define CAN_TRANSMIT_FIFO_PRIORITY_OFF 0
#define CAN_TRANSMIT_FIFO_PRIORITY_ON 1

#define CAN_DEBUG_MODE_CONTINUE 0
#define CAN_DEBUG_MODE_FREEZE 1

#define CAN_AUTO_BUS_OFF_OFF 0
#define CAN_AUTO_BUS_OFF_ON 1

#define CAN_SLEEP_INTERUPT 17
#define CAN_WAKEUP_INTERUPT 16
#define CAN_ERROR_INTERUPT 15
#define CAN_LAST_ERROR_CODE_INTERUPT 11
#define CAN_BUS_OFF_INTERUPT 10
#define CAN_ERROR_PASSIVE_INTERUPT 9
#define CAN_WARNING_INTERUPT 8
#define CAN_FIFO1_OVERRUN_INTERUPT 6
#define CAN_FIFO1_FULL_INTERNAL_INTERUPT 5
#define CAN_FIFO1_MESSAGE_PENDING_INTERUPT 4
#define CAN_FIFO0_OVERRUN_INTERUPT 3
#define CAN_FIFO0_FULL_INTERNAL_INTERUPT 2
#define CAN_FIFO0_MESSAGE_PENDING_INTERUPT 1
#define CAN_TX_MAILBOX_EMPTY_INTERUPT 0

#define CAN_NUMBER_OF_FILTER 1
#define CAN_FIFO_0_MASK 0
#define CAN_FIFO_1_MASK 1
#define CAN_ID_MASK_1_32_BIT 0b10
#define CAN_ID_MASK_2_32_BIT 0b11
#define CAN_ID_MASK_2_16_BIT 0b00
#define CAN_ID_MASK_4_16_BIT 0b01
#define CAN_FILTER_BANK_0 0
#define CAN_FILTER_BANK_1 1
#define CAN_FILTER_BANK_2 2
#define CAN_FILTER_BANK_3 3
#define CAN_FILTER_BANK_4 4
#define CAN_FILTER_BANK_5 5
#define CAN_FILTER_BANK_6 6
#define CAN_FILTER_BANK_7 7
#define CAN_FILTER_BANK_8 8
#define CAN_FILTER_BANK_9 9
#define CAN_FILTER_BANK_10 10
#define CAN_FILTER_BANK_11 11
#define CAN_FILTER_BANK_12 12
#define CAN_FILTER_BANK_13 13
#define CAN_FILTER_BANK_14 14

#define CAN_MAILBOX_0 0
#define CAN_MAILBOX_1 1
#define CAN_MAILBOX_2 2

extern const Can_ConfigType CanConfig[];
extern CAN_TypeDef *const Can_Controllers[CAN_MAX_CONTROLLER];
extern Can_ControllerStateType Can_ControllerState[CAN_MAX_CONTROLLER];
extern Can_PduType Can_TxPduInfo;
#endif