#ifndef __MCU_CFG_H__
#define __MCU_CFG_H__

#include "Mcu.h"

#define MCU_HSI_CLOCK 0
#define MCU_HSE_CLOCK_CRYSTAL 1
#define MCU_HSE_CLOCK_EXTERNAL 2
#define MCU_PLL_CLOCK_HSI 3
#define MCU_PLL_CLOCK_HSE 4

#define MCU_HSI_SYSTEM_CLOCK 0
#define MCU_HSE_SYSTEM_CLOCK 1
#define MCU_PLL_SYSTEM_CLOCK 2

#define MCU_CALIB_OFF 0
#define MCU_CALIB_ON 1

#define MCU_CSS_OFF 0
#define MCU_CSS_ON 1

#define MCU_WDT_DISABLE 0
#define MCU_WDT_ENABLE 1

#define MCU_MASTER_CLOCK_OUTPUT_DISABLE 0
#define MCU_MASTER_CLOCK_OUTPUT_ENABLE 1

#define MCU_RTC_CLOCK_OFF 0
#define MCU_RTC_CLOCK_LSE 1
#define MCU_RTC_CLOCK_LSI 2

#define MCU_CSS_DISABLE 0
#define MCU_CSS_ENABLE 1

#define MCU_PLL_DISABLE 0
#define MCU_PLL_ENABLE 1

#define MCU_PLL_SRC_HSI_DIV_2 0
#define MCU_PLL_SRC_HSE 1

#define MCU_PLL_HSE_ENTRY 0
#define MCU_PLL_HSE_ENTRY_DIV_2 1

#define MCU_PREHIRAL_AHB 0x00000557
#define MCU_PREHIRAL_APB2 0x00005FFD
#define MCU_PREHIRAL_APB1 0x3AFEC9FF

#define MCU_PLL_MULTIPLIER_1 0
#define MCU_PLL_MULTIPLIER_4 2
#define MCU_PLL_MULTIPLIER_6 3
#define MCU_PLL_MULTIPLIER_8 4
#define MCU_PLL_MULTIPLIER_9 5

#define MCU_MCO_OUTPUT_DISABLE0 0
#define MCU_MCO_OUTPUT_SRC_SYSCLOCK 4
#define MCU_MCO_OUTPUT_SRC_HSI 5
#define MCU_MCO_OUTPUT_SRC_HSE 6
#define MCU_MCO_OUTPUT_SRC_PLL_DIV_2 7

#define MCU_AHB_PRESCALE_1 0
#define MCU_AHB_PRESCALE_2 8
#define MCU_AHB_PRESCALE_4 9
#define MCU_AHB_PRESCALE_8 10
#define MCU_AHB_PRESCALE_16 11
#define MCU_AHB_PRESCALE_64 12
#define MCU_AHB_PRESCALE_128 13
#define MCU_AHB_PRESCALE_256 14
#define MCU_AHB_PRESCALE_512 15

#define MCU_APB2_PRESCALE_1 0
#define MCU_APB2_PRESCALE_2 4
#define MCU_APB2_PRESCALE_4 5
#define MCU_APB2_PRESCALE_8 6
#define MCU_APB2_PRESCALE_16 7

#define MCU_APB1_PRESCALE_1 0
#define MCU_APB1_PRESCALE_2 4
#define MCU_APB1_PRESCALE_4 5
#define MCU_APB1_PRESCALE_8 6
#define MCU_APB1_PRESCALE_16 7

#define MCU_POWER_ON_MODE 0
#define MCU_SLEEP_MODE 1
#define MCU_DEEP_SLEEP_MODE 2
#define MCU_STOP_MODE 3

#endif