#ifndef PORT_CFG_H
#define PORT_CFG_H

#include "Port.h"

#define PORT_CNF_ANALOG_INPUT 0
#define PORT_CNF_FLOATING_INPUT 1
#define PORT_CNF_PULL_UP_INPUT 2

#define PORT_CNF_GP_OUTPUT_PP 0
#define PORT_CNF_GP_OUTPUT_OD 1
#define PORT_CNF_AF_OUTPUT_PP 2
#define PORT_CNF_AF_OUTPUT_OD 3

#define PORT_MODE_INPUT 0
#define PORT_MODE_OUTPUT 1

#define PORT_OUTPUT_SPEED_10Mhz 1
#define PORT_OUTPUT_SPEED_2MHz 2
#define PORT_OUTPUT_SPEED_50MHz 3

#define PORT_A 0
#define PORT_B 1
#define PORT_C 2
#define PORT_D 3

#define NUMBER_OF_CHANNEL 3

#define PWM_CHANNEL_1 0
#define PWM_CHANNEL_2 1
#define PWM_CHANNEL_3 2
#endif